# Generated by Django 5.2.3 on 2025-06-25 18:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('register', '0002_djangouserprofile'),
    ]

    operations = [
        migrations.AlterField(
            model_name='djangouserprofile',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
